language: en
pipeline:
- name: LanguageModelTokenizer
  intent_tokenization_flag: false
  intent_split_symbol: _
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: rasa/LaBSE
  cache_dir: ./models/pretrained_models/
- name: DIETClassifier
  epochs: 100
- name: FallbackClassifier
  threshold: 0.3
- name: EntitySynonymMapper
policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 30
- name: RulePolicy
